#ifndef C8_DEF_H
#define C8_DEF_H

#define PIXEL_SCALE 10
#define VIEWPORT_WIDTH  SCREEN_WIDTH  * PIXEL_SCALE
#define VIEWPORT_HEIGHT SCREEN_HEIGHT * PIXEL_SCALE
#define PROFILER_WINDOW_WIDTH_EXTENT 0
#define PROFILER_WINDOW_HEIGHT_EXTENT 500
#define WINDOW_WIDTH  VIEWPORT_WIDTH  + PROFILER_WINDOW_WIDTH_EXTENT
#define WINDOW_HEIGHT VIEWPORT_HEIGHT + PROFILER_WINDOW_HEIGHT_EXTENT

#endif